### ISSUE TITLE
The Launcher doesn't build the project when making the project.

### ISSUE THREAD

**Issue by CodaKidGit** [ClarisoftTechnologies/codakidLauncherRelease#5]
The launcher currently doesn't run the Minecraft project creation commands until the project is opened the first time.

That's not the intended behavior. It should run the project creation commands right after the project folder is made.

When opening the project, it should just open eclipse like it does right now.

**Comment by robert-sandu** [comment]
@CodaKidGit The reasoning for running the gradle build script before opening the project for the first time was to account for creating a project by mistake. Eg: they type the wrong project name. Given that it takes a long time for gradle to finish the setup, we thought that it may be ok to run it before the first install.
But we can run it after downloading the project if this is ok for you.

**Comment by CodaKidGit** [comment]
I found that wrong names on projects aren't really a big issue. Project name isn't very important for the mod itself, and because gradle caches most of the build process anyways, building the second or third project ends up being significantly faster.

I would like to do the building first for now, if feedback comes back from our customers that is overwhelming in favor of changing, we can reconsider.
